USE mypup_db;


insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Labrador Retriever', 'Sporting', 'The sweet-faced,lovable Labrador Retriever is America''s most popular dog breed. Labs are friendly, outgoing, and high -spirited companions who have more than enough affection to go around for a family looking for a medium - to -large dog.', '$1, 200.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/31151939/Afghan-Hound-running-in-the-winter.jpg', 2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Cocker Spaniel', 'Sporting', 'The merry and frolicsome Cocker Spaniel, with his big,dreamy eyes and impish personality, is one of the worlds best - loved breeds.They were developed as huntingdogs, but Cockers gained their wide popularity as all-around companions.', '$1, 800.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/13001904/Akita-On-White-01.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Australian Shepherd', 'Herding', 'The Australian Shepherd, a lean, tough ranch dog, is one of those"only in America" stories : a European breed perfected in California by way of Australia. Fixtures on the rodeocircuit, they are closely associated with the cowboy life.', '$1, 000.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/07172037/AmStaff.06.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Border Collie', 'Herding', 'A remarkably bright workaholic,the Border Collie is an amazing dog—maybe a bit too amazing for owners without the time, energy, or means tokeep it occupied.These energetic dogs will settle down for cuddle time when the workday is done.', '$1, 500.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/03173132/Australian-Shepherd.1.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Afghan Hound', 'Hound','The Afghan Hound is an aloof and dignified aristocrat of sublime beauty. Despite his regal appearance,he is known for his profound loyalty, sensitive nature, and absolute love for those he calls his own.', '$1, 200.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/27114851/barbet.lying_.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Beagle', 'Hound', 'Not only is the Beagle an excellent hunting dog and loyal companion,it is also happy-go-lucky, funny, and—thanks to its pleading expression—cute. They were bred to hunt in packs,so they enjoy company and are generally easygoing.', '$900.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/13000937/Beagle-On-White-07.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Silky Terrier', 'Toy', 'A charming member of the AKC Toy Group, the compact,glossy - coated Silky Terrier is nonetheless a true terrier of energetic high spirits. The Silky,a native of Sydney, Australia, is larger than his close cousin, the Yorkshire Terrier.', '$1, 200.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12235957/Border-Collie-On-White-01.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id) values ('Pug', 'Toy', 'Once the mischievous companion of Chinese emperors, and later the mascot of Hollands royalHouse of Orange, the small but solid Pug is today adored by his millions of fans around the world. Pugs live to love and to be loved in return.', '$1, 500.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12235344/Bull-Terrier-On-White-03.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('French Bulldog', 'Non-Sporting', 'The one-of-a-kind French Bulldog, with his large bat ears and evendisposition, is one of the world''s most popular small - dog breeds,especially among city dwellers. The Frenchie is playful, alert, adaptable, and completely irresistible.', '$3, 000.00 ','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/18123713/Cane-Corso-AKC-121516-296.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Dalmatian', 'Non-Sporting', 'The dignified Dalmatian, dogdom''s citizen of the world, is famed for hisspotted coat and unique job description.During their long history,these "coach dogs" have accompanied the horse-drawn rigs of nobles, gypsies, and firefighters.', '$1, 500.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12213227/Cocker-Spaniel-on-White-10.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('American Staffordshire Terrier', 'Terrier', 'The American Staffordshire Terrier,known to their fans as AmStaffs, are smart, confident,good - natured companions. Their courage is proverbial. A responsibly bred,well - socialized AmStaff is a loyal, trustworthy friend to the end.', '$1, 200.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12234026/Dalmatian-On-White-01.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Bull Terrier', 'Terrier', 'Among the most comical and mischievous citizens of dogdom,the Bull Terrier is playful and endearing, sometimes stubborn,but always devoted. These unique "eggheads" are exuberant, muscular companions who thrive on affection and exercise.', '$2, 000.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/11141747/Dogo-Argentino.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Akita', 'Working', 'Akitas are muscular, double- coated dogs of ancient Japanese lineage famous for theirdignity, courage, and loyalty.In their native land,they are venerated as family protectors and symbols of good health, happiness, and long life.', '$1, 000.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/11141747/Dogo-Argentino.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Cane Corso', 'Working', 'Smart, trainable, and of noble bearing,the assertive and confident Cane Corso is a peerless protector. The Corso''s lineage goes back to ancient Roman times, andthe breed''s name roughly translates from the Latin as "bodyguard dog."', '$2, 000.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12231338/Labrador-Retriever-On-White-08.jpg',3);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Barbet', 'Miscellaneous', 'An archetypic water dog of France,the Barbet is a rustic breed of medium size and balanced proportions who appears in artwork as early as the 16th century. In profile,the Barbet is slightly rectangular with a substantial head and long, sweeping tail. He has a long,dense covering of curly hair and a distinctive beard. An agile athlete,the Barbet has been used primarily to locate, flush, and retrieve birds.He has a cheerful disposition and isvery social and loyal.', '$1, 800.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12225358/Pug-On-White-01.jpg',2);

insert into dog_posts (dog_breed, dog_group, dog_description, dog_price, images, user_id)values ('Dogo Argentino', 'Miscellaneous', 'The Dogo Argentino is a pack-hunting dog,bred for the pursuit of big-game such as wild boar and puma, and possesses the strength,intelligence and quick responsiveness of a serious athlete. His short,plain and smooth coat is completely white, but a dark patch near the eye is permitted as long as it doesn''t cover more than 10% of the head.', '$1, 000.00','https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12224133/Silky-Terrier-On-White-01.jpg',3);